[project]
name = "moeed-ul-hassan-portfolio"
version = "0.1.0"
description = "it is portfolio for moeed ul hassan"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "flask-limiter>=3.12",
]
